export const CATEGORY_SET = "CATEGORY_SET";
export const CATEGORIES_SET = "CATEGORIES_SET";
export const CATEGORY_DELETE = "CATEGORY_DELETE";
export const CATEGORY_STATE_CLEAR = "CATEGORY_STATE_CLEAR";

export const COMMENT_SET = "COMMENT_SET";
export const COMMENTS_SET = "CATEGORIES_SET";
export const COMMENT_DELETE = "COMMENT_DELETE";
export const COMMENT_APPEND = "COMMENT_APPEND";
export const COMMENT_STATE_CLEAR = "COMMENT_STATE_CLEAR";

export const DOCUMENTS_SET = "DOCUMENTS_SET";
export const DOCUMENT_APPEND = "DOCUMENT_APPEND";
export const DOCUMENT_DELETE = "DOCUMENT_DELETE";
export const DOCUMENT_SET = "DOCUMENT_SET";
export const DOCUMENT_UPDATE = "DOCUMENT_UPDATE";
export const DOCUMENT_STATE_CLEAR = "DOCUMENT_STATE_CLEAR";

export const COMMON_ERROR_SET = "COMMON_ERROR_SET";
export const COMMON_MESSAGE_SET = "COMMON_MESSAGE_SET";
export const COMMON_LOADING_SET = "COMMON_LOADING_SET";

export const ACCOUNT_SET = "ACCOUNT_SET";
export const ACCOUNTS_SET = "ACCOUNTS_SET";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

export const TRANSACTIONS_SET = "TRANSACTIONS_SET";
export const TRANSACTION_SET = "TRANSACTION_SET";
export const TRANSACTION_STATE_CLEAR = "TRANSACTION_STATE_CLEAR";

export const CENSORSHIP_SET = "CENSORSHIP_SET";
export const CENSORSHIPS_SET = "CENSORSHIPS_SET";
export const CENSORSHIP_STATE_CLEAR = "CENSORSHIP_STATE_CLEAR";

export const REPORT_SET = "REPORT_SET";
export const REPORTS_SET = "REPORTS_SET";
export const REPORTS_DETAILS_SET = "REPORTS_DETAILS_SET";
export const REPORT_STATE_CLEAR = "REPORT_STATE_CLEAR";
export const REPORT_DETAILS_STATE_CLEAR = "REPORT_DETAILS_STATE_CLEAR";

